name = "weekly-slack-bot"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[triggers]
crons = [
  "* * * * *"
]

# Environment variables
[vars]
SUPABASE_URL = "https://buiqdlquecbemsjznpft.supabase.co"

# Secrets (these are set via wrangler secret put command)
# SUPABASE_SERVICE_ROLE_KEY = set via: wrangler secret put SUPABASE_SERVICE_ROLE_KEY
# SLACK_WEBHOOK_URL = set via: wrangler secret put SLACK_WEBHOOK_URL
